"""create initial production schema

Revision ID: 5e3565570c72
Revises: 
Create Date: 2026-09-01 09:36:58.844416

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5e3565570c72'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
