"use client";

import Link from "next/link";
import { RefreshCw, Search, Siren } from "lucide-react";
import { useQuery } from "@tanstack/react-query";

import { Sidebar } from "@/components/dashboard/sidebar";
import { Topbar } from "@/components/dashboard/topbar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { DetectionEvent } from "@/lib/api/dashboard";

interface DetectionEventPage {
  items: DetectionEvent[];
  total: number;
  limit: number;
  offset: number;
}

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8001";

async function getEvents(): Promise<DetectionEventPage> {
  const response = await fetch(
    `${API_URL}/events/page?limit=25&offset=0`,
  );

  if (!response.ok) {
    throw new Error("Unable to load detection events");
  }

  return response.json() as Promise<DetectionEventPage>;
}

function severityStyle(severity: string) {
  switch (severity.toUpperCase()) {
    case "CRITICAL":
      return "border-red-200 bg-red-50 text-red-700";
    case "HIGH":
      return "border-orange-200 bg-orange-50 text-orange-700";
    case "MEDIUM":
      return "border-amber-200 bg-amber-50 text-amber-700";
    default:
      return "border-cyan-200 bg-cyan-50 text-cyan-700";
  }
}

export default function EventsPage() {
  const {
    data,
    isLoading,
    isError,
    refetch,
    isFetching,
  } = useQuery({
    queryKey: ["detection-events"],
    queryFn: getEvents,
    refetchInterval: 30_000,
  });

  return (
    <div className="flex min-h-screen bg-slate-50 text-slate-950">
      <Sidebar />

      <div className="min-w-0 flex-1">
        <Topbar />

        <main className="mx-auto max-w-[1600px] p-5 md:p-8">
          <div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
            <div>
              <div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">
                <Siren className="size-4" />
                Security Operations
              </div>

              <h1 className="text-3xl font-semibold tracking-tight">
                Detection Events
              </h1>

              <p className="mt-2 text-sm text-slate-500">
                Review intrusion detections generated by CyberSentinel AI.
              </p>
            </div>

            <Button
              variant="outline"
              onClick={() => refetch()}
              disabled={isFetching}
              className="w-fit"
            >
              <RefreshCw
                className={`size-4 ${
                  isFetching ? "animate-spin" : ""
                }`}
              />
              Refresh
            </Button>
          </div>

          <Card className="mb-6 border-slate-200 bg-white shadow-sm">
            <CardContent className="p-4">
              <div className="relative max-w-md">
                <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" />

                <Input
                  placeholder="Search IP or attack type..."
                  className="pl-10"
                />
              </div>
            </CardContent>
          </Card>

          <Card className="border-slate-200 bg-white shadow-sm">
            <CardContent className="p-0">
              {isLoading ? (
                <div className="p-10 text-center text-sm text-slate-500">
                  Loading detection events...
                </div>
              ) : isError || !data ? (
                <div className="p-10 text-center text-sm text-red-600">
                  Unable to load detection events.
                </div>
              ) : data.items.length === 0 ? (
                <div className="p-10 text-center text-sm text-slate-500">
                  No detection events found.
                </div>
              ) : (
                <>
                  <div className="overflow-x-auto">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Event ID</TableHead>
                          <TableHead>Attack Type</TableHead>
                          <TableHead>Source IP</TableHead>
                          <TableHead>Destination</TableHead>
                          <TableHead>Port</TableHead>
                          <TableHead>Confidence</TableHead>
                          <TableHead>Risk</TableHead>
                          <TableHead>Severity</TableHead>
                          <TableHead>Review</TableHead>
                        </TableRow>
                      </TableHeader>

                      <TableBody>
                        {data.items.map((event) => (
                          <TableRow key={event.id}>
                            <TableCell>
                              <Link
                                href={`/events/${event.id}`}
                                className="font-mono text-xs font-semibold text-cyan-700 hover:underline"
                              >
                                EVT-{String(event.id).padStart(5, "0")}
                              </Link>
                            </TableCell>

                            <TableCell className="font-medium">
                              {event.predicted_label}
                            </TableCell>

                            <TableCell className="font-mono text-xs">
                              {event.source_ip ?? "—"}
                            </TableCell>

                            <TableCell className="font-mono text-xs">
                              {event.destination_ip ?? "—"}
                            </TableCell>

                            <TableCell>
                              {event.destination_port ?? "—"}
                            </TableCell>

                            <TableCell>
                              {(event.classifier_confidence * 100).toFixed(1)}%
                            </TableCell>

                            <TableCell className="font-semibold">
                              {event.risk_score.toFixed(0)}/100
                            </TableCell>

                            <TableCell>
                              <Badge
                                variant="outline"
                                className={severityStyle(event.severity)}
                              >
                                {event.severity}
                              </Badge>
                            </TableCell>

                            <TableCell>
                              {event.requires_review ? (
                                <Badge className="bg-violet-100 text-violet-700">
                                  Required
                                </Badge>
                              ) : (
                                <span className="text-sm text-slate-400">
                                  —
                                </span>
                              )}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>

                  <div className="border-t border-slate-200 px-5 py-4 text-sm text-slate-500">
                    Showing {data.items.length} of {data.total} events
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </main>
      </div>
    </div>
  );
}
